apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 30001          # Puerto del servicio
      targetPort: 5000    # Puerto del contenedor
      nodePort: 30001      # Puerto expuesto en el nodo
  type: NodePort          # Tipo de servicio