name: CI/CD Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: prod
    # O si definiste otra etiqueta en tu runner, por ejemplo "windows", usar:
    # runs-on: [self-hosted, windows]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
     
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t raykhan007/my-flask-app:latest .
          docker push raykhan007/my-flask-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment flask-deployment

          
