name: CI/CD Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Login to Docker registry
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest

      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      # O bien usa otro método para configurar kubectl y credenciales

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml