name: CI/CD Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    # O si definiste otra etiqueta en tu runner, por ejemplo "windows", usar:
    # runs-on: [self-hosted, windows]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          docker login -u raykhan007 -p "Tt123456789?"

      - name: Build and push Docker image
        run: |
          docker build -t raykhan007/my-flask-app:latest .
          docker push raykhan007/my-flask-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment flask-deployment
          kubectl port-forward service/flask-service 8956:8956
